// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.particle.firmwareprotos.ctrl;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * The field numbers here are just protobuf details.  The value to pay attention to 
   * is the "int_value" option, which corresponds to the numeric value that will 
   * be set in reply frames (which itself ultimately comes from the numeric values
   * in the system_error_t enum in the firmware code).
   * </pre>
   *
   * Protobuf enum {@code particle.ctrl.ResultCode}
   */
  public enum ResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0 [(.int_value) = 0];</code>
     */
    OK(0),
    /**
     * <code>NOT_ALLOWED = 1 [(.int_value) = -130];</code>
     */
    NOT_ALLOWED(1),
    /**
     * <code>TIMEOUT = 2 [(.int_value) = -160];</code>
     */
    TIMEOUT(2),
    /**
     * <code>NOT_FOUND = 3 [(.int_value) = -170];</code>
     */
    NOT_FOUND(3),
    /**
     * <code>ALREADY_EXIST = 4 [(.int_value) = -180];</code>
     */
    ALREADY_EXIST(4),
    /**
     * <code>INVALID_STATE = 5 [(.int_value) = -210];</code>
     */
    INVALID_STATE(5),
    /**
     * <code>NO_MEMORY = 6 [(.int_value) = -260];</code>
     */
    NO_MEMORY(6),
    /**
     * <code>INVALID_PARAM = 7 [(.int_value) = -270];</code>
     */
    INVALID_PARAM(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0 [(.int_value) = 0];</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>NOT_ALLOWED = 1 [(.int_value) = -130];</code>
     */
    public static final int NOT_ALLOWED_VALUE = 1;
    /**
     * <code>TIMEOUT = 2 [(.int_value) = -160];</code>
     */
    public static final int TIMEOUT_VALUE = 2;
    /**
     * <code>NOT_FOUND = 3 [(.int_value) = -170];</code>
     */
    public static final int NOT_FOUND_VALUE = 3;
    /**
     * <code>ALREADY_EXIST = 4 [(.int_value) = -180];</code>
     */
    public static final int ALREADY_EXIST_VALUE = 4;
    /**
     * <code>INVALID_STATE = 5 [(.int_value) = -210];</code>
     */
    public static final int INVALID_STATE_VALUE = 5;
    /**
     * <code>NO_MEMORY = 6 [(.int_value) = -260];</code>
     */
    public static final int NO_MEMORY_VALUE = 6;
    /**
     * <code>INVALID_PARAM = 7 [(.int_value) = -270];</code>
     */
    public static final int INVALID_PARAM_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return NOT_ALLOWED;
        case 2: return TIMEOUT;
        case 3: return NOT_FOUND;
        case 4: return ALREADY_EXIST;
        case 5: return INVALID_STATE;
        case 6: return NO_MEMORY;
        case 7: return INVALID_PARAM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
            public ResultCode findValueByNumber(int number) {
              return ResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.particle.firmwareprotos.ctrl.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResultCode[] VALUES = values();

    public static ResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:particle.ctrl.ResultCode)
  }

  public interface IPAddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:particle.ctrl.IPAddress)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
     */
    int getProtocolValue();
    /**
     * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
     */
    io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol getProtocol();

    /**
     * <code>bytes address = 2 [(.nanopb) = { ... }</code>
     */
    com.google.protobuf.ByteString getAddress();
  }
  /**
   * Protobuf type {@code particle.ctrl.IPAddress}
   */
  public  static final class IPAddress extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:particle.ctrl.IPAddress)
      IPAddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IPAddress.newBuilder() to construct.
    private IPAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IPAddress() {
      protocol_ = 0;
      address_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IPAddress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              protocol_ = rawValue;
              break;
            }
            case 18: {

              address_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.particle.firmwareprotos.ctrl.Common.internal_static_particle_ctrl_IPAddress_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.particle.firmwareprotos.ctrl.Common.internal_static_particle_ctrl_IPAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.particle.firmwareprotos.ctrl.Common.IPAddress.class, io.particle.firmwareprotos.ctrl.Common.IPAddress.Builder.class);
    }

    /**
     * Protobuf enum {@code particle.ctrl.IPAddress.Protocol}
     */
    public enum Protocol
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>IPv4 = 1;</code>
       */
      IPv4(1),
      /**
       * <code>IPv6 = 2;</code>
       */
      IPv6(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>IPv4 = 1;</code>
       */
      public static final int IPv4_VALUE = 1;
      /**
       * <code>IPv6 = 2;</code>
       */
      public static final int IPv6_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Protocol valueOf(int value) {
        return forNumber(value);
      }

      public static Protocol forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return IPv4;
          case 2: return IPv6;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Protocol> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
              public Protocol findValueByNumber(int number) {
                return Protocol.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.particle.firmwareprotos.ctrl.Common.IPAddress.getDescriptor().getEnumTypes().get(0);
      }

      private static final Protocol[] VALUES = values();

      public static Protocol valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Protocol(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:particle.ctrl.IPAddress.Protocol)
    }

    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private int protocol_;
    /**
     * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
     */
    public int getProtocolValue() {
      return protocol_;
    }
    /**
     * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
     */
    public io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol getProtocol() {
      io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol result = io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.valueOf(protocol_);
      return result == null ? io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 2 [(.nanopb) = { ... }</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protocol_ != io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.NONE.getNumber()) {
        output.writeEnum(1, protocol_);
      }
      if (!address_.isEmpty()) {
        output.writeBytes(2, address_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protocol_ != io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, protocol_);
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.particle.firmwareprotos.ctrl.Common.IPAddress)) {
        return super.equals(obj);
      }
      io.particle.firmwareprotos.ctrl.Common.IPAddress other = (io.particle.firmwareprotos.ctrl.Common.IPAddress) obj;

      boolean result = true;
      result = result && protocol_ == other.protocol_;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + protocol_;
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.Common.IPAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.particle.firmwareprotos.ctrl.Common.IPAddress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code particle.ctrl.IPAddress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:particle.ctrl.IPAddress)
        io.particle.firmwareprotos.ctrl.Common.IPAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.particle.firmwareprotos.ctrl.Common.internal_static_particle_ctrl_IPAddress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.particle.firmwareprotos.ctrl.Common.internal_static_particle_ctrl_IPAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.particle.firmwareprotos.ctrl.Common.IPAddress.class, io.particle.firmwareprotos.ctrl.Common.IPAddress.Builder.class);
      }

      // Construct using io.particle.firmwareprotos.ctrl.Common.IPAddress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protocol_ = 0;

        address_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.particle.firmwareprotos.ctrl.Common.internal_static_particle_ctrl_IPAddress_descriptor;
      }

      public io.particle.firmwareprotos.ctrl.Common.IPAddress getDefaultInstanceForType() {
        return io.particle.firmwareprotos.ctrl.Common.IPAddress.getDefaultInstance();
      }

      public io.particle.firmwareprotos.ctrl.Common.IPAddress build() {
        io.particle.firmwareprotos.ctrl.Common.IPAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.particle.firmwareprotos.ctrl.Common.IPAddress buildPartial() {
        io.particle.firmwareprotos.ctrl.Common.IPAddress result = new io.particle.firmwareprotos.ctrl.Common.IPAddress(this);
        result.protocol_ = protocol_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.particle.firmwareprotos.ctrl.Common.IPAddress) {
          return mergeFrom((io.particle.firmwareprotos.ctrl.Common.IPAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.particle.firmwareprotos.ctrl.Common.IPAddress other) {
        if (other == io.particle.firmwareprotos.ctrl.Common.IPAddress.getDefaultInstance()) return this;
        if (other.protocol_ != 0) {
          setProtocolValue(other.getProtocolValue());
        }
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.particle.firmwareprotos.ctrl.Common.IPAddress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.particle.firmwareprotos.ctrl.Common.IPAddress) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protocol_ = 0;
      /**
       * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
       */
      public int getProtocolValue() {
        return protocol_;
      }
      /**
       * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
       */
      public Builder setProtocolValue(int value) {
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
       */
      public io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol getProtocol() {
        io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol result = io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.valueOf(protocol_);
        return result == null ? io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol.UNRECOGNIZED : result;
      }
      /**
       * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
       */
      public Builder setProtocol(io.particle.firmwareprotos.ctrl.Common.IPAddress.Protocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protocol_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.particle.ctrl.IPAddress.Protocol protocol = 1;</code>
       */
      public Builder clearProtocol() {
        
        protocol_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 2 [(.nanopb) = { ... }</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 2 [(.nanopb) = { ... }</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 2 [(.nanopb) = { ... }</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:particle.ctrl.IPAddress)
    }

    // @@protoc_insertion_point(class_scope:particle.ctrl.IPAddress)
    private static final io.particle.firmwareprotos.ctrl.Common.IPAddress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.particle.firmwareprotos.ctrl.Common.IPAddress();
    }

    public static io.particle.firmwareprotos.ctrl.Common.IPAddress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IPAddress>
        PARSER = new com.google.protobuf.AbstractParser<IPAddress>() {
      public IPAddress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IPAddress(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IPAddress> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IPAddress> getParserForType() {
      return PARSER;
    }

    public io.particle.firmwareprotos.ctrl.Common.IPAddress getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_particle_ctrl_IPAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_particle_ctrl_IPAddress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\rparticle.ctrl\032\014nanopb.pr" +
      "oto\032\020extensions.proto\"\202\001\n\tIPAddress\0223\n\010p" +
      "rotocol\030\001 \001(\0162!.particle.ctrl.IPAddress." +
      "Protocol\022\026\n\007address\030\002 \001(\014B\005\222?\002\010\020\"(\n\010Prot" +
      "ocol\022\010\n\004NONE\020\000\022\010\n\004IPv4\020\001\022\010\n\004IPv6\020\002*\370\001\n\nR" +
      "esultCode\022\014\n\002OK\020\000\032\004\220\265\030\000\022\036\n\013NOT_ALLOWED\020\001" +
      "\032\r\220\265\030\376\376\377\377\377\377\377\377\377\001\022\032\n\007TIMEOUT\020\002\032\r\220\265\030\340\376\377\377\377\377\377" +
      "\377\377\001\022\034\n\tNOT_FOUND\020\003\032\r\220\265\030\326\376\377\377\377\377\377\377\377\001\022 \n\rALR" +
      "EADY_EXIST\020\004\032\r\220\265\030\314\376\377\377\377\377\377\377\377\001\022 \n\rINVALID_S" +
      "TATE\020\005\032\r\220\265\030\256\376\377\377\377\377\377\377\377\001\022\034\n\tNO_MEMORY\020\006\032\r\220\265" +
      "\030\374\375\377\377\377\377\377\377\377\001\022 \n\rINVALID_PARAM\020\007\032\r\220\265\030\362\375\377\377\377" +
      "\377\377\377\377\001B!\n\037io.particle.firmwareprotos.ctrl" +
      "P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
          io.particle.firmwareprotos.ctrl.Extensions.getDescriptor(),
        }, assigner);
    internal_static_particle_ctrl_IPAddress_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_particle_ctrl_IPAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_particle_ctrl_IPAddress_descriptor,
        new java.lang.String[] { "Protocol", "Address", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.particle.firmwareprotos.ctrl.Extensions.intValue);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
    io.particle.firmwareprotos.ctrl.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
