// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloud.proto

package io.particle.firmwareprotos.ctrl.cloud;

public final class Cloud {
  private Cloud() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Make sure values of this enum match the values defined for the diagnostic info
   * </pre>
   *
   * Protobuf enum {@code particle.ctrl.cloud.ConnectionStatus}
   */
  public enum ConnectionStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DISCONNECTED = 0;</code>
     */
    DISCONNECTED(0),
    /**
     * <code>CONNECTING = 1;</code>
     */
    CONNECTING(1),
    /**
     * <code>CONNECTED = 2;</code>
     */
    CONNECTED(2),
    /**
     * <code>DISCONNECTING = 3;</code>
     */
    DISCONNECTING(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DISCONNECTED = 0;</code>
     */
    public static final int DISCONNECTED_VALUE = 0;
    /**
     * <code>CONNECTING = 1;</code>
     */
    public static final int CONNECTING_VALUE = 1;
    /**
     * <code>CONNECTED = 2;</code>
     */
    public static final int CONNECTED_VALUE = 2;
    /**
     * <code>DISCONNECTING = 3;</code>
     */
    public static final int DISCONNECTING_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConnectionStatus valueOf(int value) {
      return forNumber(value);
    }

    public static ConnectionStatus forNumber(int value) {
      switch (value) {
        case 0: return DISCONNECTED;
        case 1: return CONNECTING;
        case 2: return CONNECTED;
        case 3: return DISCONNECTING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConnectionStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConnectionStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConnectionStatus>() {
            public ConnectionStatus findValueByNumber(int number) {
              return ConnectionStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.particle.firmwareprotos.ctrl.cloud.Cloud.getDescriptor().getEnumTypes().get(0);
    }

    private static final ConnectionStatus[] VALUES = values();

    public static ConnectionStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConnectionStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:particle.ctrl.cloud.ConnectionStatus)
  }

  public interface GetConnectionStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:particle.ctrl.cloud.GetConnectionStatusRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Get the cloud connection status
   * </pre>
   *
   * Protobuf type {@code particle.ctrl.cloud.GetConnectionStatusRequest}
   */
  public  static final class GetConnectionStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:particle.ctrl.cloud.GetConnectionStatusRequest)
      GetConnectionStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConnectionStatusRequest.newBuilder() to construct.
    private GetConnectionStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConnectionStatusRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetConnectionStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.class, io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest)) {
        return super.equals(obj);
      }
      io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest other = (io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Get the cloud connection status
     * </pre>
     *
     * Protobuf type {@code particle.ctrl.cloud.GetConnectionStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:particle.ctrl.cloud.GetConnectionStatusRequest)
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.class, io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.Builder.class);
      }

      // Construct using io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor;
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest getDefaultInstanceForType() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.getDefaultInstance();
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest build() {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest buildPartial() {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest result = new io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest) {
          return mergeFrom((io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest other) {
        if (other == io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:particle.ctrl.cloud.GetConnectionStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:particle.ctrl.cloud.GetConnectionStatusRequest)
    private static final io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest();
    }

    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetConnectionStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetConnectionStatusRequest>() {
      public GetConnectionStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetConnectionStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetConnectionStatusRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConnectionStatusRequest> getParserForType() {
      return PARSER;
    }

    public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetConnectionStatusReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:particle.ctrl.cloud.GetConnectionStatusReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
     */
    io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus getStatus();
  }
  /**
   * Protobuf type {@code particle.ctrl.cloud.GetConnectionStatusReply}
   */
  public  static final class GetConnectionStatusReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:particle.ctrl.cloud.GetConnectionStatusReply)
      GetConnectionStatusReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConnectionStatusReply.newBuilder() to construct.
    private GetConnectionStatusReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConnectionStatusReply() {
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetConnectionStatusReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.class, io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
     */
    public io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus getStatus() {
      io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus result = io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.valueOf(status_);
      return result == null ? io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.DISCONNECTED.getNumber()) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.DISCONNECTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply)) {
        return super.equals(obj);
      }
      io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply other = (io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code particle.ctrl.cloud.GetConnectionStatusReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:particle.ctrl.cloud.GetConnectionStatusReply)
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.class, io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.Builder.class);
      }

      // Construct using io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor;
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply getDefaultInstanceForType() {
        return io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.getDefaultInstance();
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply build() {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply buildPartial() {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply result = new io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply) {
          return mergeFrom((io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply other) {
        if (other == io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
       */
      public io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus getStatus() {
        io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus result = io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.valueOf(status_);
        return result == null ? io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
       */
      public Builder setStatus(io.particle.firmwareprotos.ctrl.cloud.Cloud.ConnectionStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.particle.ctrl.cloud.ConnectionStatus status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:particle.ctrl.cloud.GetConnectionStatusReply)
    }

    // @@protoc_insertion_point(class_scope:particle.ctrl.cloud.GetConnectionStatusReply)
    private static final io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply();
    }

    public static io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetConnectionStatusReply>
        PARSER = new com.google.protobuf.AbstractParser<GetConnectionStatusReply>() {
      public GetConnectionStatusReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetConnectionStatusReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetConnectionStatusReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConnectionStatusReply> getParserForType() {
      return PARSER;
    }

    public io.particle.firmwareprotos.ctrl.cloud.Cloud.GetConnectionStatusReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_particle_ctrl_cloud_GetConnectionStatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013cloud.proto\022\023particle.ctrl.cloud\032\020exte" +
      "nsions.proto\"#\n\032GetConnectionStatusReque" +
      "st:\005\210\265\030\254\002\"Q\n\030GetConnectionStatusReply\0225\n" +
      "\006status\030\001 \001(\0162%.particle.ctrl.cloud.Conn" +
      "ectionStatus*V\n\020ConnectionStatus\022\020\n\014DISC" +
      "ONNECTED\020\000\022\016\n\nCONNECTING\020\001\022\r\n\tCONNECTED\020" +
      "\002\022\021\n\rDISCONNECTING\020\003B\'\n%io.particle.firm" +
      "wareprotos.ctrl.cloudb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.particle.firmwareprotos.ctrl.Extensions.getDescriptor(),
        }, assigner);
    internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_particle_ctrl_cloud_GetConnectionStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_particle_ctrl_cloud_GetConnectionStatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_particle_ctrl_cloud_GetConnectionStatusReply_descriptor,
        new java.lang.String[] { "Status", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.particle.firmwareprotos.ctrl.Extensions.typeId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.particle.firmwareprotos.ctrl.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
