apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'


// This is the library version used when deploying the artifact
version = '0.7.2'

ext {
    bintrayRepo = 'android'
    bintrayName = 'devicesetup'
    bintrayOrg = 'particle'

    publishedGroupId = 'io.particle'
    libraryName = 'Particle (formerly Spark) Android Device Setup library'
    artifact = 'devicesetup'

    libraryDescription = "The Particle Device Setup library provides everything you need to " +
            "offer your users a simple initial setup process for Particle-powered devices.  This " +
            "includes all the necessary device communication code, an easily customizable UI, and " +
            "a simple developer API."

    siteUrl = 'https://github.com/particle-iot/particle-android'
    gitUrl = 'https://github.com/particle-iot/particle-android.git'

    libraryVersion = project.version

    developerId = 'idok'
    developerName = 'Ido Kleinman'
    developerEmail = 'ido@particle.io'

    licenseName = 'The Apache Software License, Version 2.0'
    licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
    allLicenses = ["Apache-2.0"]
}


android {
    namespace 'io.particle.android.sdk.devicesetup'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError false
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    api project(':cloudsdk')

    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    api "io.github.microutils:kotlin-logging:1.7.8"

    api 'com.squareup.phrase:phrase:1.1.0'
    api 'io.github.inflationx:calligraphy3:3.1.1'
    api 'io.github.inflationx:viewpump:2.0.3'
    api 'com.segment.analytics.android:analytics:4.3.1'
    api 'com.madgag.spongycastle:core:1.58.0.0'

    api 'com.google.dagger:dagger:2.51.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.51.1'

    // ButterKnife (unmaintained) removed; views are bound with findViewById.

    api 'androidx.appcompat:appcompat:1.7.0'
    api 'androidx.recyclerview:recyclerview:1.3.2'
    api 'androidx.core:core-ktx:1.13.1'
    api 'com.google.code.findbugs:jsr305:3.0.2'
    api 'com.google.code.gson:gson:2.8.5'
    api 'com.squareup.okio:okio:3.9.0'
    api 'org.greenrobot:eventbus:3.0.0'
    api 'androidx.collection:collection-ktx:1.4.5'
    api 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}


// Publishing is configured in Phase 6 (Bintray is shut down; migrating to maven-publish).
// apply from: '../pom_generator_v1.gradle'
// apply from: '../bintray_upload_v1.gradle'


// Disable javadoc generation.  See this bug for more info:
// https://github.com/novoda/bintray-release/issues/71
allprojects {
    tasks.withType(Javadoc) {
        enabled = false
    }
}
