package io.particle.mesh.setup


const val ARGON_SERIAL_PREFIX1 = "ARGH"
const val ARGON_SERIAL_PREFIX2 = "ARNH"
const val ARGON_SERIAL_PREFIX3 = "ARNK"

const val XENON_SERIAL_PREFIX1 = "XENH"
const val XENON_SERIAL_PREFIX2 = "XENK"

const val BORON_LTE_SERIAL_PREFIX1 = "B40H"
const val BORON_LTE_SERIAL_PREFIX2 = "B40K"
const val BORON_3G_SERIAL_PREFIX1 = "B31H"
const val BORON_3G_SERIAL_PREFIX2 = "B31K"

const val B_SERIES_LTE_SERIAL_PREFIX1 = "P001"
const val B_SERIES_3G_SERIAL_PREFIX2 = "P002"

const val A_SERIES_SERIAL_PREFIX = "P003"
const val X_SERIES_SERIAL_PREFIX = "P004"
