/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_particle_ecjpake4j_ECJPakeImpl */

#ifndef _Included_io_particle_ecjpake4j_ECJPakeImpl
#define _Included_io_particle_ecjpake4j_ECJPakeImpl
#ifdef __cplusplus
extern "C" {
#endif


/*
* Class:     io_particle_ecjpake4j_ECJPakeImpl
* Method:    createAndInitEntropyContext
* Signature: ()Ljava/nio/ByteBuffer;
*/
JNIEXPORT jobject JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_createNativeComponents
        (JNIEnv *, jobject, jstring);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    setupJpake
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_setupJpake
        (JNIEnv *, jobject, jobject, jint, jstring);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    writeRoundOne
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_writeRoundOne
        (JNIEnv *, jobject, jobject);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    readRoundOne
 * Signature: (Ljava/nio/ByteBuffer;[B)I
 */
JNIEXPORT jint JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_readRoundOne
        (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    writeRoundTwo
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_writeRoundTwo
        (JNIEnv *, jobject, jobject);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    readRoundTwo
 * Signature: (Ljava/nio/ByteBuffer;[B)I
 */
JNIEXPORT jint JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_readRoundTwo
        (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    deriveSecret
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_deriveSecret
        (JNIEnv *, jobject, jobject);

/*
 * Class:     io_particle_ecjpake4j_ECJPakeImpl
 * Method:    freePointers
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_freePointers
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif


///*
//* Class:     io_particle_ecjpake4j_ECJPakeImpl
//* Method:    createAndInitEntropyContext
//* Signature: ()Ljava/nio/ByteBuffer;
//*/
//JNIEXPORT jobject JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_createAndInitEntropyContext
//        (JNIEnv *, jobject);
//
///*
// * Class:     io_particle_ecjpake4j_ECJPakeImpl
// * Method:    createAndInitRNGContext
// * Signature: ()Ljava/nio/ByteBuffer;
// */
//JNIEXPORT jobject JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_createAndInitRNGContext
//        (JNIEnv *, jobject);
//
///*
// * Class:     io_particle_ecjpake4j_ECJPakeImpl
// * Method:    createAndInitEcJPakeContext
// * Signature: ()Ljava/nio/ByteBuffer;
// */
//JNIEXPORT jobject JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_createAndInitEcJPakeContext
//        (JNIEnv *, jobject);

///*
// * Class:     io_particle_ecjpake4j_ECJPakeImpl
// * Method:    seedRNG
// * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/lang/String;)V
// */
//JNIEXPORT void JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_seedRNG
//        (JNIEnv *, jobject, jobject, jobject, jstring);

///*
// * Class:     io_particle_ecjpake4j_ECJPakeImpl
// * Method:    createRNGParameter
// * Signature: ()Ljava/nio/ByteBuffer;
// */
//JNIEXPORT jobject JNICALL Java_io_particle_ecjpake4j_ECJPakeImpl_createRNGParameter
//        (JNIEnv *, jobject);
