plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'jacoco'
    id 'com.github.kt3k.coveralls' version '2.12.2'
}


// Library version, also used as the Android versionName below. (Previously this module
// was published to Bintray/JCenter; that publishing has been removed.)
version = '1.0.1'


android {
    namespace 'io.particle.android.sdk.cloud'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName project.version

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-proguard-rules.pro'
    }

    testOptions {
        unitTests.all {
            testLogging {
                events "passed", "failed", "standardError"
                showCauses true
                showExceptions true
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    api "io.github.microutils:kotlin-logging:1.7.8"

    api 'com.google.code.findbugs:jsr305:3.0.2'
    api 'com.google.code.gson:gson:2.8.5'
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    api 'com.squareup.retrofit2:retrofit:2.11.0'
    api 'com.squareup.retrofit2:converter-gson:2.11.0'
    api 'org.greenrobot:eventbus:3.0.0'
    api 'androidx.collection:collection-ktx:1.4.5'
    api 'androidx.core:core-ktx:1.13.1'
    api 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'

    testImplementation 'junit:junit:4.12'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

repositories {
    maven {
        url 'https://maven.google.com'
    }
}

jacoco {
    toolVersion = "0.8.12"
    reportsDirectory = layout.buildDirectory.dir("reports")
}


coveralls {
    jacocoReportPath 'build/reports/jacocoTestReport/jacocoTestReport.xml'
}
task jacocoTestReport(type: JacocoReport, dependsOn: "testDebugUnitTest") {
    group = "Reporting"
    description = "Generate Jacoco code coverage reports for debug builds"

    reports {
        xml.required = true   // coveralls needs the xml format report
        html.required = false // no need for HTML reports when we have coveralls
    }

    def excludes = ['**/R.class',
                    '**/R$*.class',
                    '**/*$ViewBinder*.*',
                    '**/*$InjectAdapter*.*',
                    '**/*Injector*.*',
                    '**/BuildConfig.*',
                    '**/Manifest*.*',
                    '**/*Test*.*',
                    '**/*Activity*.*',
                    '**/CiMattersApplication*.*',
                    'android/**/*.*',
                    '**/*kaazing*/**/*.*'
    ]

    def debugTree = fileTree(
            dir: "$buildDir/intermediates/javac/debug/classes/io/particle/android/sdk",
            excludes: excludes)
    def kotlinDebugTree = fileTree(
            dir: "$buildDir/tmp/kotlin-classes/debug",
            excludes: excludes)
    def mainSrc = "${project.projectDir}/src/main/java"

    getClassDirectories().setFrom(files([debugTree], [kotlinDebugTree]))
    getExecutionData().setFrom(files("$buildDir/jacoco/testDebugUnitTest.exec"))
    getSourceDirectories().setFrom(files([mainSrc]))
}

