apply plugin: 'com.android.application'

android {
    namespace 'io.particle.cloudsdk.example_app'
    compileSdkVersion 35

    defaultConfig {
        applicationId "io.particle.cloudsdk.example_app"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    // BY DEFAULT, BUILD APP AGAINST THE LOCAL SDK SOURCE
    // (i.e.: make modifications to the SDK source in the local repo show up in this app
    // just by rebuilding)
    implementation project(':cloudsdk')
    //
    // **OR**
    //
    // comment out the above, and
    // UNCOMMENT THE FOLLOWING TO USE A PUBLISHED VERSION OF THE SDK:
//    implementation 'io.particle:cloudsdk:1.0.0'

    implementation 'androidx.fragment:fragment:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'org.greenrobot:eventbus:3.0.0'
}
