apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: "androidx.navigation.safeargs.kotlin"


android {
    namespace 'io.particle.mesh'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/main.kotlin_module'
    }

}

dependencies {
    implementation project(':cloudsdk')
    implementation project(':ecjpake4j')
    api project(':firmwareprotos')

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'
    implementation "io.github.microutils:kotlin-logging:1.7.8"

    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.collection:collection-ktx:1.4.5'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.8.7"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'

    implementation 'com.google.protobuf:protobuf-java:3.5.1'
    // 'com.snakydesign.livedataextensions:lives' (JCenter-only, dead) is vendored under
    // src/main/java/com/snakydesign/livedataextensions and re-exposed to dependent modules.
    implementation 'com.squareup.okio:okio:3.9.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
